apiVersion: v1
kind: Service
metadata:
  name: project-backend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: project-backend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
        group: project
    spec:
      containers:
        - name: project-backend
          image: markokoskinen2019/dwk-project-backend:v13
          resources:
            limits:
              cpu: "250m"
              memory: "50Mi"
          env:
            - name: PGPASSWORD 
              valueFrom:
                secretKeyRef:
                  name: gcpsql-postgres-config
                  key: PGPASSWORD
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: gcpsql-postgres-config
                  key: PGHOST
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: gcpsql-postgres-config
                  key: PGUSER
            - name: NATS_URL
              value: nats://default-nats.default.svc.cluster.local:4222
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3002
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3002