apiVersion: v1
kind: Service
metadata:
  name: project-backend-svc
  namespace: project
spec:
  ports:
  - port: 2345
    protocol: TCP
    targetPort: 3002
  selector:
    app: project-backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: project-backend
        group: project
    spec:
      containers:
      - env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: PGPASSWORD
              name: gcpsql-postgres-config
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: PGHOST
              name: gcpsql-postgres-config
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: PGUSER
              name: gcpsql-postgres-config
        - name: NATS_URL
          value: nats://nats.default.svc.cluster.local:4222
        image: IMAGE_PLACEHOLDER
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 20
          periodSeconds: 5
        name: project-backend
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 50Mi
