apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- deployment.yaml
- namespace.yaml
- ../../../.manifests_common/sealedsecrets/ss2.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: markokoskinen2019/dwk-project-backend
  newTag: 48bcb11f463cc6d8ca996c247b099b6898b309bb
