apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- deployment.yaml
- namespace.yaml
- ../../../.manifests_common/sealedsecrets/ss2.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: markokoskinen2019/dwk-project-backend
  newTag: f605ca8ffc1a20614464622660583f09d5994fea
