apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project-backend-dep
  namespace: project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: project-backend
      group: project
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: namespace-cpu-usage
  template:
    metadata:
      labels:
        app: project-backend
        group: project
    spec:
      containers:
        - name: project-backend
          image: markokoskinen2019/dwk-project-backend:v4
          resources:
            limits:
              cpu: "250m"
              memory: "50Mi"
          env:
            - name: PGPASSWORD 
              valueFrom:
                secretKeyRef:
                  name: gcpsql-postgres-config
                  key: PGPASSWORD
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: gcpsql-postgres-config
                  key: PGHOST
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: gcpsql-postgres-config
                  key: PGUSER
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3002
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3002