apiVersion: v1
kind: Service
metadata:
  name: project-backend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: project-backend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3002