apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot-token
  namespace: project
spec:
  encryptedData:
    BOT_TOKEN: AgB7XyWVrVlqOuESzEI+Rh3l5ZzOSZlaybo3fxNUH2T14fl+92l0BCZak2Fz2aX5RsYN1MfPgeB9GB1DwOwVRDOo2JPOadegfn1idBQTV97jUWp2vi/bT8S8ijLujHVXbe7v+ie41g45MiZAZNypilsTCJl4As99xOj0nzZlJSWY2SJRYvSkEWzvj4pp1LJlTSK5aWxJEHuGmqr2DZBmgrgUk+BD9BUXSruKCbt1CCXY+FzylCT1bFs8uI7zFxVQjbX7+9nanNcaR85mdA3iGesGB8GXOx5I1julbgiwWSbpj80w6TUYVM18g0L2GALaVCPFJJZiLhvHmDW7CtCyMCftkWnW6RfxmUIVSDfcgBEi4et0V+IgvpT7HkY/EKlc7FWMvcOXjLW2dzrAzo0vj28U1qGofFxoQ3KWFN7YbBfrupchV7yGWNBpSN7Ha5lRtGWhMPpvQx/fSL0de9QiryejG1wkDqN2jHHnzHt/X27PbYZVwLA28iKx81tAUPZq+jofgMn17AzQKLliZgvoPdiR6139SHYzoU/3PRM3jRbQMBLeeTKKuQvHrK19vrf8m/i+mA32DO9FH1RsRs7cpDcUet6vY3On4ycOXubaSw78YsBIInznoDq7AmfP4iR9m60c6H8ZpZmkaXsT+zuJHcjPLOrI9n9URlG9GsoXMB7PRSl+CwwKqr4tIMfdnMKiJ676Mj74YsPseCdylHE+pn43Ot+R0i5EuZkKHOUlN0TOlwxmiEwXCQA7F0/zS5tnZQ==
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot-token
      namespace: project

