apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcaster
        group: project
    spec:
      containers:
      - env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: BOT_TOKEN
              name: telegram-bot-token
        - name: NATS_URL
          value: nats://nats.default.svc.cluster.local:4222
        image: IMAGE_PLACEHOLDER
        name: project-backend
        resources:
          limits:
            cpu: 250m
            memory: 50Mi
