apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./namespace.yaml
- ../../../.manifests_common/sealedsecrets/ss3.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: markokoskinen2019/dwk-project-broadcaster
  newTag: 396fad62f8b7248ebeef8e6fffae668654e9e92c
