apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      containers:
        - name: mainapp
          image: markokoskinen2019/dwk-main_app:v18
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: message