apiVersion: v1
kind: Service
metadata:
  name: mainapp-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: mainapp
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      containers:
        - name: mainapp
          image: IMAGE_PLACEHOLDER
          resources:
            limits:
              cpu: "500m"
              memory: "50Mi"
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: message
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3000