apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      volumes:
        - name: shared-timestamp
          emptyDir: {}
      containers:
        - name: mainapp
          image: markokoskinen2019/dwk-main_app:v5
          volumeMounts:
          - name: shared-timestamp
            mountPath: /usr/src/app/files
        - name: timestamp-writer
          image: markokoskinen2019/dwk-timestamp-storage-app:v3
          volumeMounts:
          - name: shared-timestamp
            mountPath: /usr/src/app/files