apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- configmap.yaml
- namespace.yaml
- projectservice.yaml
- project-namespace.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: markokoskinen2019/dwk-main_app
  newTag: v29