apiVersion: v1
kind: Service
metadata:
  name: mainapp-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: mainapp
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000