apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./namespace.yaml
- ./project-namespace.yaml
- ./projectservice.yaml
- ../../.manifests_common/sealedsecrets/ss4.yaml