apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
data:
  PGPASSWORD: aGVsdmV0aW5zYWxhaW5lbg==
  PGHOST: cG9zdGdyZXMtc3ZjLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw= # postgres-svc.default.svc.cluster.local
  PGUSER: cG9zdGdyZXM= # postgres