apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secondapp
  template:
    metadata:
      labels:
        app: secondapp
    spec:
      containers:
        - name: secondapp
          image: markokoskinen2019/dwk-second_app:v19
          env:
            - name: PGPASSWORD 
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: PGPASSWORD
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: PGHOST
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: PGUSER