apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secondapp
  template:
    metadata:
      labels:
        app: secondapp
    spec:
      volumes:
      - name: shared-pong
        persistentVolumeClaim:
          claimName: pong-claim
      containers:
        - name: secondapp
          image: markokoskinen2019/dwk-second_app:v7
          volumeMounts:
          - name: shared-pong
            mountPath: /usr/src/app/files