---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./project/frontend/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: project
  validation: client

