---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dwk
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./project
  prune: true
  sourceRef:
    kind: GitRepository
    name: dwk
  validation: client

