apiVersion: v1
kind: Service
metadata:
  name: webinar-app-svc
spec:
  type: NodePort
  selector:
    app: webinar-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webinar-app
  template:
    metadata:
      labels:
        app: webinar-app
    spec:
      containers:
      - image: markokoskinen2019/dwk-webinar-app:v1
        name: webinar-app
        resources:
          limits:
            cpu: 250m
            memory: 50Mi
        ports:
        - name: web
          containerPort: 3000