apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
spec:
  type: LoadBalancer
  selector:
    app: pingpongapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001