apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: namespace-cpu-usage
  namespace: project
spec:
  metrics:
  - name: namespace-cpu-usage
    initialDelay: 1m
    successCondition: result < 20
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1618-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          scalar(avg(rate(container_cpu_user_seconds_total{namespace="project"}[10m]))*6000)