apiVersion: v1
kind: Service
metadata:
  name: project-frontend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: project-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
        group: project
    spec:
      containers:
        - name: project-frontend
          image: markokoskinen2019/dwk-project-frontend:v6
          resources:
            limits:
              cpu: "500m"
              memory: "50Mi"
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: message
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3000