apiVersion: v1
kind: Service
metadata:
  name: project-frontend-svc
  namespace: project
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: project-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: project-frontend
        group: project
    spec:
      containers:
      - image: IMAGE_PLACEHOLDER
        name: project-frontend
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 50Mi
---
