apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: markokoskinen2019/dwk-project-frontend
  newTag: ddb9576b8169c5e8f79bdbd995a3dab933253194
