apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./namespace.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: markokoskinen2019/dwk-project-frontend
  newTag: 7c70c95733cc710da93b085e2eb21d43a46922a3
