apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project-frontend-dep
  namespace: project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: project-frontend
      group: project
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: namespace-cpu-usage
  template:
    metadata:
      labels:
        app: project-frontend
        group: project
    spec:
      containers:
        - name: project-frontend
          image: markokoskinen2019/dwk-project-frontend:v3
          resources:
            limits:
              cpu: "500m"
              memory: "50Mi"
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: message
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3000