apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: todocreatorjob
  namespace: project
spec:
  schedule: "* 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todocreatorjob
            image: markokoskinen2019/dwk-todocreatorjob:v2
            env:
              - name: TODO_BACKEND_URL
                value: "http://todobackend-svc.project.svc.cluster.local:2345/"
          restartPolicy: Never