apiVersion: batch/v1
kind: Job
metadata:
  name: todocreatorjob
  namespace: project
spec:
  template:
    spec:
      containers:
      - name: todocreatorjob
        image: markokoskinen2019/dwk-todocreatorjob:v2
        env:
          - name: TODO_BACKEND_URL
            value: "http://todobackend-svc.project.svc.cluster.local:2345/"
      restartPolicy: Never # This time we'll run it only once