name: Branch Deleted
on: delete

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  delete:
    name: 'delete stuff'
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
    - name: Clean up
      run: |
        echo "Clean up for branch ${{ github.event.ref }}"

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # - run: gcloud --quiet auth configure-docker

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"


    - name: Delete GKE resources
      run: |-
        wget https://gist.githubusercontent.com/superbrothers/b428cd021e002f355ffd6dd421b75f70/raw/36200fe7db03360c40b6c97c480d91688db7f2a4/kubectl-delete_all
        chmod +x kubectl-delete_all
        kubectl config set-context --current --namespace=${{ github.event.ref }}
        ./kubectl-delete_all